name: Example Usage

on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Image to scan'
        required: true
        default: 'nginx:latest'

permissions:
  contents: write
  packages: read

jobs:
  submit:
    uses: AustonIvison/container-dependency-submitter/.github/workflows/submit-dependencies.yml@main
    with:
      image: ${{ inputs.image }}
    secrets: inherit
